
name: Deploy AWS Lambda 

on: 
  push:
    branches: #when code push on main
      - main
    paths: # only when code is changed in lambda
      - 'lambda/**'

jobs:
  deploy-lambda: # name of our job
    runs-on: ubuntu-latest # sets or specifies the runner
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python # sets up python env
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies #Install any packages
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt

    - name: Configure AWS Creds #Sets up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-west-2

    - name: Deploy Lambda Function #zips up lambda function
      run: |
        cd lambda
        zip -r lambda.zip .
        aws lambda update-function-code --function-name my-test-cicd-lambda  --zip-file fileb://lambda.zip